### PR TITLE
Add SOD-110 footprint

### PR DESCRIPTION
**Pull request by evanshultz**
SOD-110 SMT diode footprint as described at http://www.nxp.com/documents/outline_drawing/SOD110.pdf.

Image:
image

Passes all KLC checks.

### CODE REVIEW

**Comment by jkriege2** [comment]
noce work, only one change. Could you mkae the style as for all other diodes, i.e. the Silkscreen has a vertical line on the left of pad 1:
2017-01-13 19_37_58-library browser diodes_smd https___github com_kicad_diodes_smd pretty

**Comment by evanshultz** [comment]
Sure! I also re-named the package with a"D_" prefix and added the diode symbol on the fab layer.

**Comment by jkriege2** [comment]
Looks great now .... only one thing: I think you are missing the file extension `.kicad_mod` ;-) ... Please add it and I'll merge!

JAN

**Comment by evanshultz** [comment]
D'oh! Done. Thanks, Jan.

**Comment by jkriege2** [comment]
Thanks!
JAN

**Pull request merged**
