### PR TITLE
Improvements for SOD-xxx footprints

### PR DESCRIPTION
**Pull request by SchrodingersGat**
**SOD-123**
- Added package dimensions to F.Fab
- Added polarity marking to F.Fab

**SOD-323**
- Added package dimensions to F.Fab
- Added polarity marking to F.Fab

**SOD-523**
- Added package dimension to F.Fab
- Added courtyard
- Rotated 180 degrees to match other diode footprints

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
e.g. 
diode

**Comment by pointhi** [comment]
* Increase line width of F.Fab layer

**Comment by SchrodingersGat** [comment]
Duly increased

**Comment by pointhi** [comment]
thanks

**Pull request merged**
