### PR TITLE
Create D_SMB_Modified.kicad_mod

### PR DESCRIPTION
**Pull request by evanshultz**
Datasheet: http://www.littelfuse.com/~/media/electronics/datasheets/sidactors/littelfuse_sidactor_battrax_positive_negative_modified_do_214_datasheet.pdf.pdf

Image (F.Fab on top to more clearly see the diode drawing):
image

I chose to put the F.Fab drawing showing the diodes with anodes together because overlaying the diode symbols made 4 triangles with a big diamond in the middle. It looked worse to me. This isn't technically correct since there are two different diode arrangements, but since the physical package and pinout is the same I didn't want to make 2 footprints. If you have other suggestions let me know.

### CODE REVIEW

**Comment by jkriege2** [comment]
I would remove the internal diode drawings, as they will never be correct ... but please add a pin1-mark (i.e. we treat this somehow like a SOT-23 or comparable).

Also according to KLC, pin1 should be towards the top-left, so please rotate 180°

OK?

Best, JAN

**Comment by evanshultz** [comment]
Of course. Done!
image

**Comment by evanshultz** [comment]
Oops. Hang on. Silk needs to rotate too...

**Comment by evanshultz** [comment]
image

**Comment by evanshultz** [comment]
@jkriege2 Ready! And thanks for the quick review.

**Comment by poeschlr** [comment]
Pin 1 marker on fab is missing.
Maybe add a chamfer?

**Comment by evanshultz** [comment]
Sure. I suppose the old diode marking performed that function before. Image:
image

**Comment by jkriege2** [comment]
Now we cold also think about elongating the silk line at pin1 to have a pin1-mark there too (IMHO not absolutely necessary, as the package is not rotation-invariant).

Best,
JAN

**Comment by evanshultz** [comment]
Why not? Here it is:
image

**Comment by jkriege2** [comment]
Nice work!
JAN

**Pull request merged**
