### PR TITLE
Create DO-214AC.kicad_mod

### PR DESCRIPTION
**Pull request by savenlid**
from vishay datasheet

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hey @savenlid can you please adjust the polarization marks on the silkscreen as below?

A lot of the diode footprints are old and not very good. Thanks for your contribution of this one.

do

**Comment by jkriege2** [comment]
Isn't that the same as SMA: https://en.wikipedia.org/wiki/DO-214 ?

**Comment by evanshultz** [comment]
@jkriege2 Yes, it is.
@SchrodingersGat @poeschlr @savenlid If this PR isn't needed, can it be closed?

It may be worthwhile to add more info in the footprint descriptions to have "DO-214AC" along with SMA for clarity. But that's a different task. I'll do it for the SMx footprints if nobody else wants to.

**Comment by SchrodingersGat** [comment]
Thanks @evanshultz . I'll close this one for now.

**Pull request closed without merging**
