### PR TITLE
adding DO-214AB module

### PR DESCRIPTION
**Pull request by hyOzd**
Module is designed according to footprint suggestion in [Fairchild SS32 datasheet](https://www.fairchildsemi.com/datasheets/SS/SS34.pdf).

1mm extra pad length is added for hand soldering version.

### CODE REVIEW

**Comment by michal777** [comment]
DO-214AB is different name of SMC so only one of them should be in this library. This DO-214AB shouldn't replace SMC if it hasn't 3d model.
1-pin mark should be visible after assembly, good example of SOD/DO is here: http://www.pcblibraries.com/forum/smt-library-silkscreen-outlines_topic26.html

**Comment by hyOzd** [comment]
Sorry... I didn't know that. It's even mentioned in the datasheet a couple times. But I haven't noticed that it's a package name.

I've created a 3d model for DO-214AB which I think looks better then current model for SMC.

do_214_ab

Also as you can see from above render, 1st pin should be visible after assembly. Are you suggesting me to draw it as an extended line as shown in the referenced forum post?

**Comment by michal777** [comment]
Looks great. If you could add it to kicad-library repo this DO-214AB should replace SMC.
The silkscreen for Polarized Chip, Polarized Molded Body, Small Outline Diode (SOD) from the link I sent is compatible with IPC-7351C and it would be better to redraw it.

**Comment by michal777** [comment]
Thanks for contribution.

**Pull request merged**
