### PR TITLE
Add Powermite footprints

### PR DESCRIPTION
**Pull request by evanshultz**
More updating and moving parts from SMD_Packages (https://github.com/KiCad/SMD_Packages.pretty/issues/20).

In addition to Powermite3, I created the other two (I can't find any parts using Powermite2 online, but I suppose it doesn't hurt to have the footprint.

The Microsemi nor On Semi drawings show the alignment of the part to the copper. I contacted Microsemi and was told they don't have a recommended alignment, but they guess the best option to the center the anode (small) lead in the anode pad. Surprising, but more than I got from On Semi or Diodes Inc (who make or used to make parts in this package). It seems reasonable, so that's what I did.

Powermite3 has three pins, and you can see at https://www.hybridelectronics.com/images/cataloug/m/Powermite.pdf there are single diode and common cathode parts that fit in this package. However, we should be fine since we have suitable symbols in the library already:
image
image

Image:
image

### CODE REVIEW

**Comment by evanshultz** [comment]
Could a librarian please take a look at these footprints? Thank you!

**Comment by jkriege2** [comment]
Hi!

I see a few issues:
1. Please add `D_`as prefix to the filename/footprintname (to match all other names in this repo)
2. Powermit/Powermite2: usually pin1 is cathode/K (at least for all the diodes in device.lib), but in this footprint, the kathode of e.g. MBRM140T1G would be connected to pin 2, i.e. please swap pin-numbers (and rotate the footprint then by 180°). In https://www.onsemi.com/pub/Collateral/457-04.PDF the have three styles, one with K /marking at the housing, one with K/marking at the longer pin and one without marking. I think style 2 (no marking) can be omitted for this lib, but Style 1 and 3 should be present as two variants. Please adopt some style of naming as for `D_SOT-23_...` in this lib!

Best,
JAN

**Comment by evanshultz** [comment]
@jkriege2 
Is there an excess of diode symbols? I believe you made the dual symbols, Jan, so were these made to fit the existing footprints or did you create every diode permutation? I understand KLC 7.6 to be saying don't make extra footprints but instead make multiple symbols, but there are so many.

For Powermite3, https://www.microsemi.com/document-portal/doc_view/14814-powermite-surface-mount-power-packages shows 2 configurations on page 10. I assume we should do both, but because there is every possible diode symbol how to determine the pinout of the footprint? I just chose something that works, but as a user it would be unclear which schematic symbol to use.

For Powermite/Powermite2, I added the little diode symbol on F.Fab in addition to your suggestions above. I used an `_AK` suffix if the big pin is the cathode since that seems "correct" to me, and also all Powermite diodes I found online from all vendors were of this configuration.

How are these?
image

Note that I selected separate models on Powermite/Powermite3 since the cathode mark on the parts will be different. For Powermite3, I think a common 3D model is fine.

**Comment by evanshultz** [comment]
I should have stated that if these look OK toy you I'll add the D_ prefix and update this PR. I'd like a review first since this feels subjective and I picked what seems good to me.

**Comment by jkriege2** [comment]
Hi!

I think the diodes are just a slight bit messy ... the way I drew the symbols (based on what was there in the lib before and the example set by the transistors ... and some specific rules):
1. single-diodes exist in one variant only: K=1, A=2 (this is universal, also for PDs or LEDs). This way you can match any 2-pin `D_`-package to any diode symbol + we have the variants of SOT-23 with one pin unused
2. If you want a special diode in a special package ... you can alsways make an atomic symbol for that diode
3. The double diodes and single-diodes with 3rd pin should exist in all permutations.

Therefore you PowerMit3 is/was fine and can be left as it initially was (one variant). PowerMite and PowerMite2 sould be fine as you suggested them above!

Best,
JAN

**Comment by evanshultz** [comment]
@jkriege2 
Should be all done. They look like this (before I added the `D_` prefix):
image

**Comment by jkriege2** [comment]
Looks good to me!

Thanks,
JAN

**Pull request merged**
