### PR TITLE
added SMD bridge rectifier packages

### PR DESCRIPTION
**Pull request by jkriege2**
2017-05-16 21_18_22-pcbnew d__temp_testtemp_testtemp kicad_pcb

references:
- http://www.vishay.com/docs/88854/padlayouts.pdf
- http://www.vishay.com/docs/89959/mbl104s.pdf

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hi Jan,

It looks like the pin-1 marking is overlaid by the default soldermask expansion. Can you move the pin-1 lines up a little bit to avoid this?

**Comment by SchrodingersGat** [comment]
@jkriege2 just a small change here and we can merge :)

**Comment by jkriege2** [comment]
DONE ... OK?
JAN

**Comment by SchrodingersGat** [comment]
Thanks Jan

**Pull request merged**
