### PR TITLE
adding new footprints + swapping A/K pins

### PR DESCRIPTION
**Pull request by ricardocrudo**
The footprint looks like this:
screenshot_2015-02-27_08-05-14

I don't know if is ok put the diode symbol in the center, but I think it makes clear the cathode and anode.

### CODE REVIEW

**Comment by michal777** [comment]
There is a problem with pins numbering - you used the standard numbering but other diodes in kicad library use pin 1 for anode. I think that it's safer to keep one numbering in kicad libraries.

**Comment by ricardocrudo** [comment]
Following this PDF (http://goo.gl/zbiU5M) that you've posted the cathode is the pin with longer line and it should be the pin 1, right?
KiCad uses anode as pin 1 and following KLC pin 1 shoud sit on left. 
If I follow the PDF does it means that I'll have to solder the part in reverse way?

**Comment by michal777** [comment]
Longer line indicates pin 1. Pin 1 should be cathode but in kicad library it's anode so maybe anode should have longer line but it will be opposite to some ipc standards...
Maybe it's better to change all diodes in kicad library to have the standard numbering.
I think we will need to wait for opinions of other librarians.

**Comment by CarlPoirier** [comment]
Hi,

Yes, it indeed will be better to flip them all. In fact, they need to be redesigned. Ricardo, do you want to undertake this? Your symbol at the top is good, the only thing I'd say is maybe shorten the silkscreen lines a tiny bit to have a little bit of spacing between them and the courtyard.

**Comment by ricardocrudo** [comment]
Sure, I can do it. I'm with tight time, but I'll do it ASAP. Just to be sure about the task, it is redesign the footprints of all diode and inverse all diodes pins numbers, of all schematic libraries, right?

**Comment by ricardocrudo** [comment]
The diodes symbols also had A/K swaped at symbols KiCad/kicad-library#175.

**Comment by CarlPoirier** [comment]
Hi Ricardo,

You will need to rotate the 3D packages for Diode_SMA_Standard and Diode_SMC_Standard. Besides that, I think it's good to go!

**Comment by CarlPoirier** [comment]
Awesome!! Thanks Ricardo.

**Pull request merged**
