### PR TITLE
Create D_SOT-23_ANK for single diodes in SOT23

### PR DESCRIPTION
**Pull request by evanshultz**
This is the PR for issue [#910](https://github.com/KiCad/kicad-library/issues/910), starting from the package text I showed there:
- Added a rectangle (3.0x1.4mm) and diode symbol to fab layer.
- Moved courtyard to meet the 0.25mm spacing in KLC.
- Changed silk lines to 0.12mm.
- Rounded coordinates to 1/100 of a mm.

Image:
image

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

two things:
1. could you please base this symbol on the footprint from `TO_SOT_Packages_SMT` (style!):
2017-01-16 22_29_24-library browser to_sot_packages_smd https___github com_kicad_to_sot_packages
BTW: I like the small diode inside ;-)
2. Could you also provide the variants NKA (see e.g. http://www.vishay.com/docs/85535/bal99.pdf) ... and others if you should find any ;-)

Best,
JAN

**Comment by evanshultz** [comment]
1. Done.
2. Sure. I don't know of other variants.

**Comment by jkriege2** [comment]
Very nice now ... only one things remains before I can merge: F.Fab uses a linewidth of 0.15, but should be 0.1mm1

Please fix.

best,
JAN

**Comment by evanshultz** [comment]
Thank you and sorry. Odd that this wasn't caught by check_kicad_mod.py.

Done. This is also a problem with `TO_SOT_Packages_SMD.pretty:SOT-23.kicad_mod`. I'll fix it in https://github.com/KiCad/TO_SOT_Packages_SMD.pretty/pull/26.

**Comment by jkriege2** [comment]
did yo use the most current script version?
JAN

Otherwise: nice work!

**Comment by evanshultz** [comment]
Oops! This is wrong. K is pin 1 and A is pin 2, so the ANK and KNA are backwards (both need pins 1 and 2 swapped). Can I fix this here or do I need another PR?

**Comment by evanshultz** [comment]
Or rename these symbols to _1N2 and _2N1? Probably easier for a user if it's _ANK and _NKA, though. PR #29 submitted.

**Pull request merged**
