### PR TITLE
Added SOD323 footprint

### PR DESCRIPTION
**Pull request by mistoll**
Comments appreciated

### CODE REVIEW

**Comment by michal777** [comment]
Some KiCad Library Convention rules are broken. There silkscreen is wrong (paint over pads), there is no courtyard, the name should be SOD-323.
It's SMD, so the Attributes in Footprint Properties should be set to Normal+Insert.
At the moment there are no rules in KLC how to fill Reference and Value, but probably it looks better if they are default: Refernce the same as name, Value is VAL**

**Comment by mistoll** [comment]
Hi, 
Silkscreen: fixed
Name: fixed (Diode_SOD-323) (Rules 7.2, 9.2)
Attributes: fixed
Reference/Value: fixed

Courtyard: How is it applied in KiCad? Just expand the silk?

I'm going to update the commit.

**Comment by michal777** [comment]
You've added two footprints: Diode-SOD323.kicad_mod and Diode_SOD-323.kicad_mod

Rule 9.2 doesn't apply because SOD323 isn't specific device, but package (may be sth else than diode). SOD-323.kicad_mod will be better.

The rule 6.8 is broken - the name in the file is Diodes_SMD:Diode-SOD323
- first line is: (module Diodes_SMD:Diode-SOD323 (layer F.Cu) (tedit 54AE3818)
By the way, I think it's bug in KiCad that the library name that you unnecessarily added was ignored in file name but wasn't ignored inside .kicad_mod file.

The fields in footprint properties should be:
Reference: SOD-323 (not VAL**)
Value: VAL**
Footprint Name in Library: SOD-323 (don't add library name).

To satisfy rule 6.5 the silkscreen may be as in "Small Outline Diode (SOD)" on page:
http://www.pcblibraries.com/forum/smt-library-silkscreen-outlines_topic26.html
It will allow to recognise cathode after assembly.

**Comment by mistoll** [comment]
The name should be right now. But that's not consistent with the other components in Diodes_SMD any more.

Nice article about the silkscreen. Footprint updated.

BTW: How does KiCad know what data to give to the pick and place machines?

**Comment by michal777** [comment]
Courtyard is not rounded to 0.05mm.

**Comment by michal777** [comment]
Probably courtyard should be thinner and not overlaping silkscreen, I will ask on mailing list about that.

**Comment by michal777** [comment]
Sorry for not responding for so long. The courtyard is good (will be described in next revision of library convention). The value should be VAL** and reference the same as filename (they are swapped). The rule that line width should be 0.15 mm applies to text line width so please edit it.

**Comment by mistoll** [comment]
Better?

**Comment by michal777** [comment]
Yes, now all is OK. Thanks for contibution.

**Pull request merged**
