### PR TITLE
Added PowerDI-123

### PR DESCRIPTION
**Pull request by SchrodingersGat**
- Rotated 180 degrees to match other diodes
- Added package outline to F.Fab layer
- Added polarity indication to F.Fab
- Improvements to silkscreen
- Improved text placement
- Improved courtyard

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
powerdi-123

**Comment by pointhi** [comment]
```
checking module: PowerDI-123
  Violating Rule 10.7
    3D Shape ".wrl" files are named the same as their footprint and are placed in a folder named the
    same as the footprint library replacing the ".pretty" with ".3dshapes".
  Violating Rule 6.4
    For surface-mount devices, footprint anchor is placed in the middle with respect to device lead
    ends. (IPC-7351).
```

**Comment by SchrodingersGat** [comment]
Fixed, thanks

**Comment by pointhi** [comment]
@CarlPoirier: what do you think?

```
checking module: PowerDI-123
  Violating Rule 6.4
    For surface-mount devices, footprint anchor is placed in the middle with respect to device lead
    ends. (IPC-7351).
```

**Comment by jkriege2** [comment]
Up?

**Comment by SchrodingersGat** [comment]
I have updated this to match new KLC. It still fails 6.4 because the pads are not centered on the package. However, I think it makes most sense to center on the package rather than the midpoint of pads (because that is where the PnP machine will grab it!

( I think that KLC6.4 should potentially be changed to reflect these cases )

**Comment by SchrodingersGat** [comment]
Ugh, sorry for PR noise. Hit "rebase"  instead of "merge" again.

**Comment by SchrodingersGat** [comment]
Ignore this - I have fixed in https://github.com/KiCad/Diodes_SMD.pretty/pull/30

**Pull request closed without merging**
