### PR TITLE
normalizing modules aligned to 3D models 

### PR DESCRIPTION
**Pull request by easyw**
D_SOD-123 D_SOD-323
to be aligned to 
https://github.com/KiCad/packages3D/pull/33

### CODE REVIEW

**Comment by easyw** [comment]
Violating Rule 10.4
    3D model reference
    Model path should start with '${KISYS3DMOD}/'
Is that a new rule?
I don't see this on other pretty modules

**Comment by SchrodingersGat** [comment]
@easyw the ${KISYS3DMOD} is an allowance for the way that the nightly builds save the 3D reference data. Not mandatory.

Please fix the actual errors though - "%R" missing from F.Fab layer. Thanks.

**Comment by SchrodingersGat** [comment]
@easyw  refer to the travis logs, looks like you have edited the wrong text items

**Comment by Shackmeister** [comment]
@easyw perhaps this one should be finished so it can be merged? :) currently the models doesnt align since this hasnt been merged

**Comment by easyw** [comment]
@SchrodingersGat @Shackmeister 
it should be fixed now

**Comment by SchrodingersGat** [comment]
Thanks :)

**Pull request merged**
