### PR TITLE
Add Microsemi LSM115J

### PR DESCRIPTION
**Pull request by GyrosGeier**
Manufacturer recommended footprint for LSM115J

### CODE REVIEW

**Comment by keruseykaryu** [comment]
This housing has its own name: DO-214BA. Please use this name instead of manufacturer part name.

**Comment by mangelajo** [comment]
This uses to happen quite usually. Im wondering if we could keep a list of
manufacturer ids per footprint or schema part. This way when users look for
an specific part they can find the right plugin...

**Comment by GyrosGeier** [comment]
Adjusted, sending new pull request

**Comment by GyrosGeier** [comment]
Adjusted the footprint.

**Comment by keruseykaryu** [comment]
Do you have a possibility to add a courtyard (You need a one of recent KiCad)?

**Comment by GyrosGeier** [comment]
I have no experience with pick'n'place machines, so I have no idea how much space I should reserve for this to be generally useful -- otherwise I'd just use the outline.

**Comment by keruseykaryu** [comment]
Read the KLC from here: https://github.com/KiCad/kicad-library/blob/master/KiCad_Library_Convention.txt Section 6.

**Comment by GyrosGeier** [comment]
Done.

**Comment by CarlPoirier** [comment]
Thanks for your contribution!

**Pull request merged**
